In [3]:
import numpy as np

In [4]:
my_lst=[1,2,3,4,5]

In [5]:
arr=np.array(my_lst)

In [6]:
arr

array([1, 2, 3, 4, 5])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(5,)

In [9]:
my_lst1=[1,2,3,4,5]
my_lst2=[6,7,8,9,10]
my_lst3=[11,12,13,14,15]
arr1=np.array([my_lst1,my_lst2,my_lst3])

In [10]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [11]:
arr1.shape

(3, 5)

In [12]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [13]:
arr1.reshape

<function ndarray.reshape>

In [14]:
arr

array([1, 2, 3, 4, 5])

In [15]:
arr[0]#indexing single dimension

1

In [16]:
arr1[0][2] #indexing double dimension

3

In [17]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
arr1[0:2,1:2]

array([[2],
       [7]])

In [20]:
arr=np.arange(0,10)

In [21]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr2=np.arange(0,10,step=2)

In [23]:
arr2

array([0, 2, 4, 6, 8])

In [24]:
arr3=np.linspace(0,10,20)

In [25]:
arr3

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [28]:
arr[3:]=100 #broadcasting

In [29]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [30]:

arr1=arr
arr1[3:]=500
print(arr1)
print(arr)

[  0   1   2 500 500 500 500 500 500 500]
[  0   1   2 500 500 500 500 500 500 500]


In [31]:
#Copy Function
arr1=arr.copy()

In [32]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [33]:
arr1[3:]=600


In [34]:
arr1

array([  0,   1,   2, 600, 600, 600, 600, 600, 600, 600])

In [35]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [36]:
a=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [37]:
arr*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [38]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [39]:
arr[arr<2]

array([0, 1])

In [40]:
arr[arr<500]

array([0, 1, 2])

In [41]:
np.ones(4)

array([1., 1., 1., 1.])

In [42]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [43]:
arr1=np.arange(1,10)
arr2=np.arange(1,10)

In [44]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
arr1*arr2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [51]:
np.random.rand(3,4)

array([[0.50897809, 0.41657133, 0.67116984, 0.96605092],
       [0.20517378, 0.42949606, 0.71249231, 0.92991314],
       [0.23788417, 0.38541351, 0.78022846, 0.07683994]])

In [55]:
np.random.randn(4,4) #based on standard normal distribution

array([[ 0.950005  ,  1.24522829,  0.76455593, -0.98759733],
       [-0.68308517, -1.87870177, -0.39333268,  0.45028388],
       [ 0.05958008, -0.08375324,  0.47021862,  0.2399911 ],
       [-0.08112795,  0.09636451, -0.53403648, -0.57300891]])

In [58]:
np.random.randint(0,100,8).reshape(4,2)

array([[20, 69],
       [28, 99],
       [ 8,  3],
       [75, 86]])

In [59]:
np.random.random_sample((1,5))

array([[0.01110192, 0.6452801 , 0.72093405, 0.04398163, 0.49078961]])